# Generated by Django 3.0.6 on 2020-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBook', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
