# Generated by Django 3.0.6 on 2020-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBook', '0003_auto_20200510_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start',
            field=models.DateField(),
        ),
    ]
