# Generated by Django 3.0.6 on 2020-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBook', '0006_destination_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
