# Generated by Django 3.0.6 on 2020-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBook', '0007_destination_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date(mm/dd/yy)'),
        ),
    ]
